# Generated by Django 3.2 on 2021-04-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_variacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variável', 'verbose_name_plural': 'Variações'},
        ),
        migrations.AddField(
            model_name='variacao',
            name='preco',
            field=models.FloatField(default=0),
        ),
    ]
